### ISSUE TITLE
nhplate 命名问题

### ISSUE THREAD

**Issue by abc3660170** [netheroes/nhplate#2]
建议 改名为 nh-plate

**Comment by cz-dot** [comment]
我觉得应该不会改了叭

**Comment by hideyuki** [comment]
Original repository name is "nhplate".

<img width="374" alt="スクリーンショット 2019-06-26 23 17 39" src="https://user-images.githubusercontent.com/159752/60187806-30d89880-9869-11e9-892a-e92d177c8f70.png">
